#!/sbin/busybox sh

# $1 - "above_hispeed_delay_sleep"
# $2 - value=

if [ "a$2" != "a" ]; then
	above_hispeed_delay_sleep=$2;

	echoPath="/sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay";

	if [ -f $echoPath ]; then
		case "${above_hispeed_delay_sleep}" in
			battery)
				echo "20000 1000000:20000 1200000:30000" > $echoPath;
			;;
			default)
				echo "20000 1000000:40000 1200000:80000" > $echoPath;
			;;
			performance)
				echo "20000 1000000:40000 1200000:80000" > $echoPath;
			;;
			*)
				above_hispeed_delay_sleep=default;
			;;
		esac;
	fi;
fi;

echo ${above_hispeed_delay_sleep};

