#!/sbin/busybox sh

if [ "a$2" != "a" ]; then
	bootmenu_enabled=$2

	case "${bootmenu_enabled}" in
		0)
			touch /mnt/sdcard/.nobootlogo;
		;;
		1)
			if [ -e /mnt/sdcard/.nobootlogo ]; then
				rm -f /mnt/sdcard/.nobootlogo;
			fi;
		;;
	esac;
fi;

echo "${bootmenu_enabled}";

