#!/sbin/busybox sh

if [ "a$2" != "a" ]; then

	PROFILE=`cat /data/.siyah/.active.profile`;
	. /data/.siyah/$PROFILE.profile;

	filename=$(basename "$2");

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		newfreq="$3";
		evalcmd='eval "$filename=$newfreq"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;

		if [ -f $2 ]; then
			if [ "$newfreq" == "1000000" ] && [ "$scaling_max_freq_oc" -ge "1000000" ]; then
				echo "$scaling_max_freq_oc" > $2;
			else
				echo "$newfreq" > $2;
			fi;
		fi;
	fi;
fi;

