#!/sbin/busybox sh

if [ "a$2" != "a" ]; then

	filename=$(basename "$2");

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
		MAX_FREQ_NOW=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`;
		if [ "$MAX_FREQ_NOW" == "1000000" ] || [ "$MAX_FREQ_NOW" -ge "1000000" ]; then
				echo "$3" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
		fi;
	fi;
fi;

