#!/sbin/busybox sh

if [ "a$2" != "a" ]; then

	filename=$(basename "$2");

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
		case "$3" in
			off)
				pkill -f "gesture_set.sh";
				pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture";
			;;
			on)
				pkill -f "gesture_set.sh";
				pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture";
				/sbin/busybox sh /data/gesture_set.sh;
			;;
		esac;
	fi;
fi;

