#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  lowmemkiller=$2
fi

mount -o remount,rw /

case "${lowmemkiller}" in
        low)
			echo "1024,1024,1280,8192,16384,32768" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "64" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		medium)
			echo "1024,2048,2560,12288,16384,32768" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "48" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		default)
			echo "1024,2048,4096,12288,16384,32768" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		aggressive)
			echo "2048,4096,8192,16384,24576,32768" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		exterminate)
			echo "4096,8192,16384,19200,32768,32768" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "8" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		*)
			lowmemkiller=medium;
		;;
	esac;
fi;
