#!/sbin/busybox sh
# $1 - "negative_tweak"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$negative_tweak";
else
	negative_tweak=$2;
	echo "$negative_tweak";
fi;

case "${negative_tweak}" in
	1)
		kmemhelper -n homekey_trg_cnt -t int 4 > /dev/null 2>&1;
	;;
	2)
		kmemhelper -n homekey_trg_cnt -t int 6 > /dev/null 2>&1;
	;;
	3)
		kmemhelper -n homekey_trg_cnt -t int 0 > /dev/null 2>&1;
	;;
	*)
		negative_tweak=1;
	;;
esac;

