#!/sbin/busybox sh

# $1 - "target_loads_sleep"
# $2 - value=

if [ "a$2" != "a" ]; then
	target_loads_sleep=$2;

	echoPath="/sys/devices/system/cpu/cpufreq/interactive/target_loads";

	if [ -f $echoPath ]; then
		case "${target_loads_sleep}" in
			battery)
				echo "70 600000:75 700000:80 800000:85 1000000:90" > $echoPath;
			;;
			default)
				echo "60 900000:70 1000000:80" > $echoPath;
			;;
			performance)
				echo "60 900000:65 1000000:70" > $echoPath;
			;;
			*)
				target_loads_sleep=default;
			;;
		esac;
	fi;
fi;

echo ${target_loads_sleep};

