#!/sbin/busybox sh

if [ "a$3" == "a" ]; then
	evalcmd='eval "echo \$TOUCHSCREEN$2"';
	eval $evalcmd;
else
	evalcmd='eval "TOUCHSCREEN$2=$3"';
	eval $evalcmd;
	evalcmd='eval "echo \$TOUCHSCREEN$2"';
	eval $evalcmd;
fi;

if [ -f /sys/devices/virtual/sec/sec_touchscreen/tsp_touch_config ]; then
	echo "$TOUCHSCREEN1 $TOUCHSCREEN2 $TOUCHSCREEN3 $TOUCHSCREEN4 $TOUCHSCREEN5 $TOUCHSCREEN6" > /sys/devices/virtual/sec/sec_touchscreen/tsp_touch_config;
fi;

