#!/sbin/busybox sh
cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys
echo 102 > /sys/devices/virtual/sec/sec_key/set_homekey

if grep -q bootmode=2 /proc/cmdline ; then
cp -a /res/misc/init.40/* /
echo 0 > /proc/sys/kernel/rom_feature_set
cp -a /recovery.rc /init.rc
exec /sbin/init2
fi
if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
# low power mode
echo 0 > /proc/sys/kernel/rom_feature_set
cp -a /res/misc/init.40/* /
cp lpm.rc init.rc
rm init.smdk4210.rc
chmod 755 /innt
chmod 644 /*.rc
chmod 644 /*.prop
exec /sbin/init2
fi

SECONDROM=1
NOBOOTLOGO=0
mkdir -p /dev/block
mkdir /dev/input
mkdir /dev/graphics
mknod /dev/graphics/fb0 c 29 0
mknod /dev/input/event1 c 13 65
mknod /dev/input/event2 c 13 66
mknod /dev/input/event8 c 13 72
mknod /dev/input/event9 c 13 73
mknod /dev/ashmem c 10 61
mknod /dev/block/mmcblk0p1 b 179 1
mknod /dev/block/mmcblk0p7 b 179 7
mknod /dev/block/mmcblk0p9 b 259 1
mknod /dev/block/mmcblk0p10 b 259 2
mknod /dev/block/mmcblk0p11 b 259 3
mknod /dev/block/mmcblk0p12 b 259 4
mknod /dev/block/loop0 b 7 0

mkdir -p /mnt/.secondrom
chmod 755 /mnt
mkdir /preload
mount -t ext4 -o ro /dev/block/mmcblk0p12 /preload

mount -t vfat /dev/block/mmcblk0p11 /mnt
NEXTBOOT=`cat /mnt/.nextboot`
rm -f /mnt/.nextboot
DEFAULTROM=`cat /mnt/.defaultrom`
SECONDROM=1
NOBOOTLOGO=0
[ -f /preload/build.prop ] || SECONDROM=0
[ -f /mnt/.secondrom/data.img ] || SECONDROM=0
[ -f /mnt/.secondrom/cache.img ] || SECONDROM=0
[ -f /mnt/.nobootlogo ] && NOBOOTLOGO=1
umount /preload
umount /mnt

if [ "$SECONDROM" == "0" ];then
if [ "$NOBOOTLOGO" == "0" ];then
/sbin/choose_rom $SECONDROM
fi
else
if [ "$NEXTBOOT" == "1" ];then
SECONDROM=0;
elif [ "$NEXTBOOT" == "2" ];then
SECONDROM=1;
else
if [ "$NOBOOTLOGO" == "1" ];then
SECONDROM=$DEFAULTROM
elif [ "$DEFAULTROM" == "1" ];then
/sbin/choose_rom $SECONDROM
if [ "$?" == "1" ]; then
SECONDROM=0
else
SECONDROM=1
fi
else
/sbin/choose_rom $SECONDROM
if [ "$?" == "1" ]; then
SECONDROM=1
else
SECONDROM=0
fi
fi
fi
fi

if [ "$SECONDROM" == "1" ]; then
rm -rf /res/dev
mkdir -p /res/dev
ln -s /mnt/.secondrom/.secondrom/data.img /res/dev/data
ln -s /dev/block/mmcblk0p12 /res/dev/system
ln -s /mnt/.secondrom/.secondrom/cache.img /res/dev/cache
else
rm -rf /res/dev
mkdir -p /res/dev
ln -s /dev/block/mmcblk0p10 /res/dev/data
ln -s /dev/block/mmcblk0p9 /res/dev/system
ln -s /dev/block/mmcblk0p7 /res/dev/cache
fi

mount -t ext4 /res/dev/system /system

# copy new Kernel modules to /system/lib/modules and to second rom system if exist
if [ ! -d /system/lib/modules ]; then
mkdir /system/lib/modules;
cp /lib/modules/*.ko /system/lib/modules/;
chmod 755 /system/lib/modules/*.ko;
else
cp /lib/modules/*.ko /system/lib/modules/;
chmod 755 /system/lib/modules/*.ko;
fi;

if [ -f /system/recovery.cpio.gz ]; then
mount -o remount,rw /;
zcat /system/recovery.cpio.gz | cpio -idmu;
fi;

# efs check and fix, do not change.
sh -c "/sbin/e2fsck -fyc /dev/block/mmcblk0p1" > /tmp/efs_check 2>&1;
sh -c "/sbin/e2fsck -p /dev/block/mmcblk0p1" >> /tmp/efs_check 2>&1;
mount -t ext4 /dev/block/mmcblk0p1 /efs;
chmod -R 777 /efs
umount /efs;

CM101=1

if [ "$CM101" == 1 ];
then
echo 3 > /proc/sys/kernel/rom_feature_set
rm -rf /vendor
mv -f /res/misc/init.cm10.1/* /
fi

if [ "$SECONDROM" == "1" ];then
mv /init.smdk4210.rc.2 /init.smdk4210.rc
mv /init.rc.2 /init.rc
else
rm -f /init.rc.2 /init.smdk4210.rc.2
fi

umount /system
rm -rf /res/misc/init*
chmod 755 /innt
chmod 644 /*.smdk4210
chmod 644 /*.rc
chmod 644 /*.prop
chmod -R 755 /lib

# cpu undervolting interfaces
insmod /lib/modules/cpu_undervolting.ko

exec /sbin/init2
